# -*- coding: utf-8 -*-
"""hubspot_audit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tDYPsbo1S-E5z45jh2kN5aDGydqP7OG0
"""

import requests
import json
import pandas as pd
import os  # <--- Standard Python library for environment variables

# 1. SETUP: Securely fetch token from environment variables
# In a real project, keys are stored in a .env file or system variables, not hardcoded.
# Users running this must set 'HUBSPOT_TOKEN' in their environment.

ACCESS_TOKEN = os.getenv('HUBSPOT_TOKEN')

# Safety check: Stop the script if no token is found
if not ACCESS_TOKEN:
    raise ValueError("❌ Error: HUBSPOT_TOKEN is missing. Please set it in your environment variables.")

HEADERS = {
    'Authorization': f'Bearer {ACCESS_TOKEN}',
    'Content-Type': 'application/json'
}

def run_governance_audit():
    url = "https://api.hubapi.com/crm/v3/objects/deals"

    # We request the core fields + the custom fields we created
    # Note: HubSpot usually keeps internal names lowercase (e.g., 'emis_merchant_name')
    params = {
        'properties': 'dealname,dealstage,amount,emis_merchant_name,emis_gmv_actual,data_hygiene_flag',
        'limit': 100
    }

    print("🚀 Fetching deals from HubSpot...")
    response = requests.get(url, headers=HEADERS, params=params)

    if response.status_code != 200:
        print(f"❌ Error: {response.status_code} - {response.text}")
        return

    deals = response.json().get('results', [])
    audit_results = []

    print(f"🔎 Auditing {len(deals)} records for Snapmint Process Governance...\n")

    for deal in deals:
        deal_id = deal['id']
        p = deal['properties']

        name = p.get('dealname', 'N/A')
        stage = p.get('dealstage', 'N/A')
        emis_name = p.get('emis_merchant_name')
        gmv = p.get('emis_gmv_actual')

        status = "Green" # Default
        reason = "Passed all checks"

        # GOVERNANCE LOGIC 1: Merchant Mapping (Snapmint JD requirement)
        if stage == 'closedwon' and not emis_name:
            status = "Red"
            reason = "CRITICAL: Closed Won but no EMIS Merchant Name"

        # GOVERNANCE LOGIC 2: GMV Tracking Accuracy
        elif not gmv or float(gmv) <= 0:
            status = "Yellow"
            reason = "WARNING: Missing or zero GMV data"

        # Update the status back to HubSpot
        update_hubspot_flag(deal_id, status)

        # Collect for the final report
        audit_results.append({
            "Deal Name": name,
            "Stage": stage,
            "EMIS Name": emis_name,
            "GMV": gmv,
            "Hygiene Status": status,
            "Audit Note": reason
        })

    # Display the final report in a professional table
    df = pd.DataFrame(audit_results)
    print("\n--- FINAL GOVERNANCE REPORT ---")
    return df

def update_hubspot_flag(deal_id, color):
    """Writes the audit status back to the HubSpot record"""
    url = f"https://api.hubapi.com/crm/v3/objects/deals/{deal_id}"
    payload = {"properties": {"data_hygiene_flag": color}}
    requests.patch(url, headers=HEADERS, data=json.dumps(payload))

# EXECUTE
report_df = run_governance_audit()
report_df